---
framework: "jest"
blocklist:
  - "jest-tests/alibaba.spec.js##Alibaba Search"
postMerge:
  pattern:
    - "./jest-tests/*.js"
preMerge:
  pattern:
    - "./jest-tests/*.js"
preRun:
  - npm i
postRun:
  - echo 'runAgain'
version: 2.0